name: Validate

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: HACS Validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest Validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master